### PR TITLE
Use temp directory for GPKG in tests

### PR DESCRIPTION
**Pull request by ilyankou**
Addresses #263 

Uses `pytest`'s `tmp_path` to write GPKG files inside a temporary directory. The files are then deleted automatically after the tests complete: https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html

### CODE REVIEW

**Comment by ilyankou** [comment]
Hi @anitagraser 

There must be an issue with GitHub checks (failing on setting up conda pre-tests in most environments).

But the second commit should resolve #363:

- Trajectory's `clip()` method relies on `_get_segments_for_ranges()`
- `_get_segments_for_ranges()` returns a list of segments (Trajectories) whose `.id`s are clean, but whose `.df` values in traj ID column have timestamps from when they were created by `Trajectory.get_segment_between()`
- These timestamped values from traj ID column are then copied directly by `Trajectory._to_line_df()` / `Trajectory.to_line_gdf()`  and `Trajectory.to_point_gdf()`

**Comment by anitagraser** [comment]
Thank you, Ilya. I've fixed the error in the test setup which was due to some parts being deprecated. 

Please sync this change so the tests can run.

**Comment by anitagraser** [comment]
Great. Could you also add a test that addresses #363 to ensure that the issue is fixed and doesn't reappear in the future?

**Comment by anitagraser** [comment]
(In general, it's cleaner to have one PR per issue)

**Comment by ilyankou** [comment]
I added a single test case to *test_overlay.py*'s `def test_clip_one_intersections(self)`:

```python
# make sure traj ids are clean and not timestamped:
assert intersections.get_trajectory("1_0").df.traj_id.unique() == ["1_0"]
```

I think it's better suited here as a *clip* issue rather than the downstream `to_line_gdf()`/`to_point_gdf()` but let me know if you disagree and/or if you think we need an extra function like `to_line_gdf_after_clipping()` for a TrajectoryCollection.

The old/original code would fail like this:
```zsh
=========================== short test summary info ============================
FAILED movingpandas/tests/test_overlay.py::TestOverlay::test_clip_one_intersections -
AssertionError: assert array(['1_197... dtype=object) == ['1_0']
```

**Pull request merged**
